import comp from "/Users/carson/Desktop/Mister-Hope.github.io-main/src/.vuepress/.temp/pages/en/index.html.vue"
const data = JSON.parse("{\"path\":\"/en/\",\"title\":\"Home\",\"lang\":\"en-US\",\"frontmatter\":{\"date\":\"2022-01-07T00:00:00.000Z\",\"home\":true,\"layout\":\"BlogHome\",\"icon\":\"home\",\"title\":\"Home\",\"heroImage\":\"/logo.svg\",\"heroText\":\"𝓜𝓻. 𝓗𝓸𝓹𝓮\",\"tagline\":\"Where there is light, there is hope\",\"bgImage\":\"https://file.mo7.cc/api/public/bz\",\"heroFullScreen\":true,\"projects\":[{\"name\":\"VuePress\",\"desc\":\"Vue-powered Static Site Generator\",\"link\":\"https://vuejs.press/\",\"icon\":\"/assets/img/vuepress.png\"},{\"name\":\"VuePress Theme Hope\",\"desc\":\"A VuePress theme with tons of features✨\",\"link\":\"https://theme-hope.vuejs.press/\",\"icon\":\"https://theme-hope.vuejs.press/logo.svg\"},{\"name\":\"Waline\",\"desc\":\"A safe and fast comment service\",\"link\":\"https://waline.js.org/en/\",\"icon\":\"https://waline.js.org/logo.png\"},{\"name\":\"markdown-it plugins\",\"desc\":\"Powerful markdown-it plugins written in typescript\",\"link\":\"https://mdit-plugins.github.io/\",\"icon\":\"https://mdit-plugins.github.io/logo.svg\"},{\"name\":\"in NENU\",\"desc\":\"800,000+ words NENU guide, a comprehensive introduction to NENU life, the best admission guide for NENU freshmen❤\",\"link\":\"https://innenu.com\",\"icon\":\"/assets/img/inNENU.png\"},{\"name\":\"vuepress-plugin-md-enhance\",\"desc\":\"VuePress Markdown Enhance plugin\",\"link\":\"https://plugin-md-enhance.vuejs.press/\",\"icon\":\"https://plugin-md-enhance.vuejs.press/logo.svg\"},{\"name\":\"bcrypt-ts\",\"icon\":\"project\",\"desc\":\"Bcrypt written in typescript\",\"link\":\"https://github.com/Mister-Hope/bcrypt-ts\"},{\"name\":\"@mr-hope/gulp-sass\",\"type\":\"project\",\"desc\":\"Sass Plugin for Gulp\",\"link\":\"https://github.com/Mister-Hope/gulp-sass\"},{\"name\":\"mptool\",\"desc\":\"Light, effective mini-app framework\",\"link\":\"https://github.com/miniapp-tool/mptool\",\"icon\":\"https://miniapp-tool.github.io/logo.png\"}],\"head\":[[\"link\",{\"rel\":\"alternate\",\"hreflang\":\"zh-cn\",\"href\":\"https://mister-hope.com/\"}],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://mister-hope.com/en/\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"My name is Mr.Hope\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Home\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"website\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"og:locale:alternate\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2022-01-07T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"WebPage\\\",\\\"name\\\":\\\"Home\\\"}\"]]},\"headers\":[],\"readingTime\":{\"minutes\":0.65,\"words\":196},\"filePathRelative\":\"en/README.md\",\"localizedDate\":\"January 7, 2022\",\"excerpt\":\"\"}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
