import comp from "/Users/carson/Desktop/Mister-Hope.github.io-main/src/.vuepress/.temp/pages/code/language/js/guide/get-started.html.vue"
const data = JSON.parse("{\"path\":\"/code/language/js/guide/get-started.html\",\"title\":\"快速上手\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"快速上手\",\"icon\":\"creative\",\"date\":\"2019-09-14T00:00:00.000Z\",\"category\":\"JavaScript\",\"tag\":[\"快速上手\"],\"description\":\"提示 因为 JavaScript 是一门编程语言，不再是 HTML 和 CSS 这种看得见摸得着的东西，所以我们从如何引入、运行并调试开始讲起。\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://mister-hope.com/code/language/js/guide/get-started.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Mr.Hope\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"快速上手\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"提示 因为 JavaScript 是一门编程语言，不再是 HTML 和 CSS 这种看得见摸得着的东西，所以我们从如何引入、运行并调试开始讲起。\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"快速上手\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2019-09-14T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"快速上手\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2019-09-14T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Mr.Hope\\\",\\\"url\\\":\\\"https://mister-hope.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"练习方法\",\"slug\":\"练习方法\",\"link\":\"#练习方法\",\"children\":[]},{\"level\":2,\"title\":\"JavaScript 的引入\",\"slug\":\"javascript-的引入\",\"link\":\"#javascript-的引入\",\"children\":[]},{\"level\":2,\"title\":\"JavaScript 的编写\",\"slug\":\"javascript-的编写\",\"link\":\"#javascript-的编写\",\"children\":[]},{\"level\":2,\"title\":\"JavaScript 的运行\",\"slug\":\"javascript-的运行\",\"link\":\"#javascript-的运行\",\"children\":[{\"level\":3,\"title\":\"浏览器运行\",\"slug\":\"浏览器运行\",\"link\":\"#浏览器运行\",\"children\":[]},{\"level\":3,\"title\":\"架设本地服务器\",\"slug\":\"架设本地服务器\",\"link\":\"#架设本地服务器\",\"children\":[]},{\"level\":3,\"title\":\"使用 Node.js\",\"slug\":\"使用-node-js\",\"link\":\"#使用-node-js\",\"children\":[]}]},{\"level\":2,\"title\":\"JavaScript 的调试\",\"slug\":\"javascript-的调试\",\"link\":\"#javascript-的调试\",\"children\":[{\"level\":3,\"title\":\"浏览器\",\"slug\":\"浏览器\",\"link\":\"#浏览器\",\"children\":[]},{\"level\":3,\"title\":\"Node.js\",\"slug\":\"node-js\",\"link\":\"#node-js\",\"children\":[]},{\"level\":3,\"title\":\"VS Code\",\"slug\":\"vs-code\",\"link\":\"#vs-code\",\"children\":[]}]}],\"readingTime\":{\"minutes\":4.2,\"words\":1261},\"filePathRelative\":\"code/language/js/guide/get-started.md\",\"localizedDate\":\"2019年9月14日\",\"excerpt\":\"<div class=\\\"hint-container tip\\\">\\n<p class=\\\"hint-container-title\\\">提示</p>\\n<p>因为 JavaScript 是一门编程语言，不再是 HTML 和 CSS 这种看得见摸得着的东西，所以我们从如何引入、运行并调试开始讲起。</p>\\n</div>\\n\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
