<template><div><h1 id="dd" tabindex="-1"><a class="header-anchor" href="#dd"><span>dd</span></a></h1>
<p><code v-pre>dd</code> 命令用于复制磁盘或文件系统。</p>
<h2 id="复制磁盘" tabindex="-1"><a class="header-anchor" href="#复制磁盘"><span>复制磁盘</span></a></h2>
<div class="language-bash" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">dd</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> if=/dev/sda</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> of=/dev/sdb</span></span></code></pre>
</div><p>上面命令表示将<code v-pre>/dev/sda</code> 磁盘复制到<code v-pre>/dev/sdb</code> 设备。参数 <code v-pre>if</code> 表示来源地，<code v-pre>of</code> 表示目的地。</p>
<p>除了复制，<code v-pre>dd</code> 还允许将磁盘做成一个镜像文件。</p>
<div class="language-bash" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">dd</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> if=/dev/sda</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> of=/home/username/sdadisk.img</span></span></code></pre>
</div><p><code v-pre>dd</code> 还可以复制单个分区。</p>
<div class="language-bash" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">dd</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> if=/dev/sda2</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> of=/home/username/partition2.img</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> bs=</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">4096</span></span></code></pre>
</div><p>上面命令中，参数 <code v-pre>bs</code> 表示单次拷贝的字节数(bytes)。</p>
<p>要将镜像文件复原，也很简单。</p>
<div class="language-bash" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">dd</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> if=sdadisk.img</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> of=/dev/sdb</span></span></code></pre>
</div><h2 id="清除数据" tabindex="-1"><a class="header-anchor" href="#清除数据"><span>清除数据</span></a></h2>
<p><code v-pre>dd</code> 也可以用于清除磁盘数据。</p>
<div class="language-bash" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 磁盘数据写满 0</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> dd</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> if=/dev/zero</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> of=/dev/sda1</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 磁盘数据写满随机字符</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> dd</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> if=/dev/urandom</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> of=/dev/sda1</span></span></code></pre>
</div><h2 id="监控进展" tabindex="-1"><a class="header-anchor" href="#监控进展"><span>监控进展</span></a></h2>
<p>磁盘的复制通常需要很久，为了监控进展，可以使用 Pipe Viewer 工具软件。如果没有安装这个软件，可以使用下面的命令安装。</p>
<div class="language-bash" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">sudo</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> apt</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> install</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> pv</span></span></code></pre>
</div><p>然后，来源地和目的地之间插入广告，就可以看到进展了。</p>
<div class="language-bash" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> dd</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> if=/dev/urandom</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> | </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">pv</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> | </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">dd</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> of=/dev/sda1</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">4,14MB</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 0:00:05</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> [ </span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">98kB/s]</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> [      &#x3C;=>                  </span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">]</span></span></code></pre>
</div><h2 id="参考链接" tabindex="-1"><a class="header-anchor" href="#参考链接"><span>参考链接</span></a></h2>
<ul>
<li>David Clinton, <a href="https://opensource.com/article/18/7/how-use-dd-linux" target="_blank" rel="noopener noreferrer">How to use dd in Linux without destroying your disk</a></li>
</ul>
</div></template>


