<template><div><h1 id="lpq" tabindex="-1"><a class="header-anchor" href="#lpq"><span>lpq</span></a></h1>
<p><code v-pre>lpq</code> 命令显示打印机队列。</p>
<div class="language-bash" data-highlighter="shiki" data-ext="bash" data-title="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre v-pre class="shiki shiki-themes one-light one-dark-pro vp-code"><code><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">$</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> lpq</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Rank</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">    Owner</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">   Job</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">     File</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">s</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)                         </span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">Total</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Size</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">active</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">  adnanad</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 59</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">      demo</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">                            399360</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> bytes</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">1st</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">     adnanad</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 60</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">      (stdin)                         0 bytes</span></span></code></pre>
</div></div></template>


