import comp from "/Users/carson/Desktop/Mister-Hope.github.io-main/src/.vuepress/.temp/pages/en/software/nginx.html.vue"
const data = JSON.parse("{\"path\":\"/en/software/nginx.html\",\"title\":\"Nginx\",\"lang\":\"en-US\",\"frontmatter\":{\"date\":\"2020-05-04T00:00:00.000Z\",\"icon\":\"nginx\",\"description\":\"Nginx Intro Nginx is a high performance HTTP and reverse proxy server and an IMAP / POP3 / SMTP proxy server. It features low memory, high concurrency, high stability, and Nginx...\",\"head\":[[\"link\",{\"rel\":\"alternate\",\"hreflang\":\"zh-cn\",\"href\":\"https://mister-hope.com/software/nginx.html\"}],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://mister-hope.com/en/software/nginx.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"My name is Mr.Hope\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Nginx\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Nginx Intro Nginx is a high performance HTTP and reverse proxy server and an IMAP / POP3 / SMTP proxy server. It features low memory, high concurrency, high stability, and Nginx...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"og:locale:alternate\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2020-05-04T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Nginx\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2020-05-04T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Mr.Hope\\\",\\\"url\\\":\\\"https://mister-hope.com\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"Intro\",\"slug\":\"intro\",\"link\":\"#intro\",\"children\":[]},{\"level\":2,\"title\":\"Starting, Stopping, and Reloading Configuration\",\"slug\":\"starting-stopping-and-reloading-configuration\",\"link\":\"#starting-stopping-and-reloading-configuration\",\"children\":[]},{\"level\":2,\"title\":\"Configuration File’s Structure\",\"slug\":\"configuration-file-s-structure\",\"link\":\"#configuration-file-s-structure\",\"children\":[]},{\"level\":2,\"title\":\"Serving Static Content\",\"slug\":\"serving-static-content\",\"link\":\"#serving-static-content\",\"children\":[]},{\"level\":2,\"title\":\"Setting Up a Simple Proxy Server\",\"slug\":\"setting-up-a-simple-proxy-server\",\"link\":\"#setting-up-a-simple-proxy-server\",\"children\":[]},{\"level\":2,\"title\":\"Setting Up FastCGI Proxying\",\"slug\":\"setting-up-fastcgi-proxying\",\"link\":\"#setting-up-fastcgi-proxying\",\"children\":[]},{\"level\":2,\"title\":\"Official Docs\",\"slug\":\"official-docs\",\"link\":\"#official-docs\",\"children\":[]}],\"readingTime\":{\"minutes\":4.72,\"words\":1415},\"filePathRelative\":\"en/software/nginx.md\",\"localizedDate\":\"May 4, 2020\",\"excerpt\":\"\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
